### ISSUE TITLE
User Story [Artour]

### ISSUE THREAD

**Issue by AmberMLiu** [echefuru/Lucky-Aces#7]
After selecting Blackjack and pressing “Play”, the user is taken to a Blackjack game view, where they can play Blackjack against the program dealer. They can select to Hit or Hold in each round. At the end of each round the outcome is displayed and tallied as Player Wins and Dealer Wins. The user can exit back to the Game Library view at any time.

- “Play” use case: At the starting screen of the game, the user can select “Play” to start a round. The user is dealt two cards, and the dealer one. If the user is immediately dealt 21, the game automatically moves to the “Hold” use case. If the user has <21, they can choose to Hit or Hold.
- “Hit” use case: The user can repeatedly select “Hit” to be dealt another card as long as they have <21. If the user gets 21 at any point in this stage, the game automatically moves to the “Hold” use case. If the user gets >21 at any point in this stage, the user goes bust and the round ends as a win for the dealer.
- “Hold” use case: The user can select to “Hold” to lock in their hand and move to the stage where the dealer draws their cards. The user will draw until they get >16 or they bust. Then their hand value is compared to that of the user, and the result of win, lose, or draw is displayed and tallied across rounds.
- “Again” use case: At the end of each round the user can select to play again, which clears all dealt cards and starts another round of Blackjack.
- “Exit” use case: At any point in the game the user can select to exit which takes them back to the Game Library. The tally of wins and losses is also reset.

**Comment by artourguoft** [comment]
Closed by https://github.com/echefuru/Lucky-Aces/pull/28.
